name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib=3.8.0
  - numpy=1.24.4
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - tqdm=4.66.1
  - pip
  - pip:
    - torch==2.0.1
    - torchvision==0.15.2
